apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: simulator-poste
  labels:
    app: simulator-poste-backend
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  OIDC_ISSUER: "https://kyma.accounts.ondemand.com"
  # Frontend URL for CORS
  FRONTEND_URL: "https://simulator-poste.b66a502.kyma.ondemand.com"
